package products

import "devllart/foobarman/internal/texts"

var AvailableProducts = map[string]ProductInfo{
    "Absente Absinthe 110 Proof": {
      Name:          "Absente Absinthe 110 proof",
      Type:          "Абсент",
      Alc:           55.00,
      Taste:         GetTaste("Абсент"),
      AviableVolume: []float64{0.100, 0.750},
      Prices:        []float64{11.32, 48.99},
      Description:   &texts.DescProduct[0],
    },
    "Jim Beam Bourbon Whiskey": {
      Name:          "Jim Beam Bourbon Whiskey",
      Type:          "Бурбон",
      Alc:           40.00,
      Taste:         GetTaste("Бурбон"),
      AviableVolume: []float64{1.000, 1.750},
      Prices:        []float64{24.99, 31.99},
      Description:   &texts.DescProduct[1],
    },
    "Jack Daniel'S Old No. 7 Tennessee Whiskey": {
      Name:          "Jack Daniel's Old No. 7 Tennessee Whiskey",
      Type:          "Виски",
      Alc:           40.00,
      Taste:         GetTaste("Виски"),
      AviableVolume: []float64{0.750, 1.000},
      Prices:        []float64{26.60, 36.99},
      Description:   &texts.DescProduct[2],
    },
    "Irish Manor Irish Cream": {
      Name:          "Irish Manor Irish Cream",
      Type:          "Айриш крим",
      Alc:           17.00,
      Taste:         GetTaste("Айриш крим"),
      AviableVolume: []float64{0.750, 1.750},
      Prices:        []float64{14.99, 26.12},
      Description:   &texts.DescProduct[3],
    },
    "Клубничное Пюре": {
      Name:          "Клубничное Пюре",
      Type:          "Клубничное пюре",
      Alc:           0.00,
      Taste:         GetTaste("Клубничное пюре"),
      AviableVolume: []float64{1.000},
      Prices:        []float64{1.00},
      Description:   &texts.DescProduct[4],
    },
    "Малина": {
      Name:          "Малина",
      Type:          "Малина",
      Alc:           0.00,
      Taste:         GetTaste("Малина"),
      AviableVolume: []float64{1.000},
      Prices:        []float64{1.00},
      Description:   &texts.DescProduct[5],
    },
    "Клубника": {
      Name:          "Клубника",
      Type:          "Клубника",
      Alc:           0.00,
      Taste:         GetTaste("Клубника"),
      AviableVolume: []float64{1.000},
      Prices:        []float64{1.00},
      Description:   &texts.DescProduct[6],
    },
    "Fruko Schulz Coffee Liqueur": {
      Name:          "Fruko Schulz coffee liqueur",
      Type:          "Кофейный ликер Fruko Schulz",
      Alc:           20.00,
      Taste:         GetTaste("Кофейный ликер Fruko Schulz"),
      AviableVolume: []float64{0.700},
      Prices:        []float64{20.55},
      Description:   &texts.DescProduct[7],
    },
    "Amaretto Liqueur Fruko Schulz": {
      Name:          "Amaretto Liqueur Fruko Schulz",
      Type:          "Ликер амаретто Fruko Schulz",
      Alc:           25.00,
      Taste:         GetTaste("Ликер амаретто Fruko Schulz"),
      AviableVolume: []float64{0.700},
      Prices:        []float64{20.45},
      Description:   &texts.DescProduct[8],
    },
    "Сливки \"ПРОСТОКВАШИНО\"": {
      Name:          "Сливки \"ПРОСТОКВАШИНО\"",
      Type:          "Сливки",
      Alc:           0.00,
      Taste:         GetTaste("Сливки"),
      AviableVolume: []float64{0.200},
      Prices:        []float64{1.00},
      Description:   &texts.DescProduct[9],
    },
    "Monin Cinnamon Bun": {
      Name:          "Monin Cinnamon Bun",
      Type:          "Сироп корицы",
      Alc:           0.00,
      Taste:         GetTaste("Сироп корицы"),
      AviableVolume: []float64{0.750},
      Prices:        []float64{7.99},
      Description:   &texts.DescProduct[10],
    },
    "Jolly Roger Gold Rum": {
      Name:          "Jolly Roger Gold Rum",
      Type:          "Золотой ром",
      Alc:           40.00,
      Taste:         GetTaste("Золотой ром"),
      AviableVolume: []float64{0.750},
      Prices:        []float64{12.99},
      Description:   &texts.DescProduct[11],
    },
    "Stroh Rum 160 Proof": {
      Name:          "Stroh Rum 160 Proof",
      Type:          "Сверхкрепкий ром",
      Alc:           80.00,
      Taste:         GetTaste("Сверхкрепкий ром"),
      AviableVolume: []float64{0.750},
      Prices:        []float64{33.99},
      Description:   &texts.DescProduct[12],
    },
    "Monster Energy Drink": {
      Name:          "Monster Energy Drink",
      Type:          "Энергетик",
      Alc:           0.00,
      Taste:         GetTaste("Энергетик"),
      AviableVolume: []float64{0.473},
      Prices:        []float64{2.99},
      Description:   &texts.DescProduct[13],
    },
    "Red Bull": {
      Name:          "Red Bull",
      Type:          "Энергетик",
      Alc:           0.00,
      Taste:         GetTaste("Энергетик"),
      AviableVolume: []float64{0.248, 0.473},
      Prices:        []float64{2.89, 4.59},
      Description:   &texts.DescProduct[14],
    },
    "BACARDI Black Rum": {
      Name:          "BACARDI Black Rum",
      Type:          "Темный ром",
      Alc:           40.00,
      Taste:         GetTaste("Темный ром"),
      AviableVolume: []float64{0.200, 0.750},
      Prices:        []float64{5.49, 15.49},
      Description:   &texts.DescProduct[15],
    },
    "BACARDI Spiced Rum": {
      Name:          "BACARDI Spiced Rum",
      Type:          "Ром",
      Alc:           35.00,
      Taste:         GetTaste("Ром"),
      AviableVolume: []float64{0.750, 1.750},
      Prices:        []float64{15.89, 24.14},
      Description:   &texts.DescProduct[16],
    },
    "Barsmith Grenadine": {
      Name:          "Barsmith Grenadine",
      Type:          "Гренадин",
      Alc:           0.00,
      Taste:         GetTaste("Гренадин"),
      AviableVolume: []float64{0.354},
      Prices:        []float64{4.99},
      Description:   &texts.DescProduct[17],
    },
    "Barsmith Simple Syrup": {
      Name:          "Barsmith Simple Syrup",
      Type:          "Сахарный сироп",
      Alc:           0.00,
      Taste:         GetTaste("Сахарный сироп"),
      AviableVolume: []float64{0.360},
      Prices:        []float64{4.99},
      Description:   &texts.DescProduct[18],
    },
    "Bell'S Original Blended Scotch Whisky": {
      Name:          "Bell'S Original Blended Scotch Whisky",
      Type:          "Шотландский виски",
      Alc:           40.00,
      Taste:         GetTaste("Шотландский виски"),
      AviableVolume: []float64{0.750},
      Prices:        []float64{16.81},
      Description:   &texts.DescProduct[19],
    },
    "Belsazar Vermouth": {
      Name:          "Belsazar Vermouth",
      Type:          "Красный вермут",
      Alc:           40.00,
      Taste:         GetTaste("Красный вермут"),
      AviableVolume: []float64{0.375, 0.750},
      Prices:        []float64{7.99, 13.19},
      Description:   &texts.DescProduct[20],
    },
    "Bioniq Mint": {
      Name:          "Bioniq Mint",
      Type:          "Мята",
      Alc:           0.00,
      Taste:         GetTaste("Мята"),
      AviableVolume: []float64{0.035},
      Prices:        []float64{1.09},
      Description:   &texts.DescProduct[21],
    },
    "Bombay Dry Gin": {
      Name:          "Bombay Dry Gin",
      Type:          "Лондонский сухой джин",
      Alc:           43.00,
      Taste:         GetTaste("Лондонский сухой джин"),
      AviableVolume: []float64{0.750, 1.750},
      Prices:        []float64{22.99, 34.49},
      Description:   &texts.DescProduct[22],
    },
    "Bonduelle Olives": {
      Name:          "Bonduelle Olives",
      Type:          "Оливки",
      Alc:           0.00,
      Taste:         GetTaste("Оливки"),
      AviableVolume: []float64{0.300},
      Prices:        []float64{1.49},
      Description:   &texts.DescProduct[23],
    },
    "Bud": {
      Name:          "Bud",
      Type:          "Пиво",
      Alc:           5.90,
      Taste:         GetTaste("Пиво"),
      AviableVolume: []float64{0.500},
      Prices:        []float64{1.10},
      Description:   &texts.DescProduct[24],
    },
    "Bud Light": {
      Name:          "Bud Light",
      Type:          "Пиво",
      Alc:           4.70,
      Taste:         GetTaste("Пиво"),
      AviableVolume: []float64{0.500},
      Prices:        []float64{1.70},
      Description:   &texts.DescProduct[25],
    },
    "Cherry Bomb Cocktail Syrup": {
      Name:          "Cherry Bomb Cocktail Syrup",
      Type:          "Сахарный сироп",
      Alc:           0.00,
      Taste:         GetTaste("Сахарный сироп"),
      AviableVolume: []float64{0.400},
      Prices:        []float64{19.00},
      Description:   &texts.DescProduct[26],
    },
    "Coca-Cola": {
      Name:          "Coca-Cola",
      Type:          "Кола",
      Alc:           0.00,
      Taste:         GetTaste("Кола"),
      AviableVolume: []float64{0.500, 1.000, 1.500, 2.000},
      Prices:        []float64{1.00, 2.00, 3.00, 4.00},
      Description:   &texts.DescProduct[27],
    },
    "Cointreau Orange Liqueur Triple Sec": {
      Name:          "Cointreau Orange Liqueur Triple Sec",
      Type:          "Трипл сек",
      Alc:           40.00,
      Taste:         GetTaste("Трипл сек"),
      AviableVolume: []float64{0.750, 1.000},
      Prices:        []float64{40.65, 45.97},
      Description:   &texts.DescProduct[28],
    },
    "Collins Simple Syrup Cocktail Mix": {
      Name:          "Collins Simple Syrup Cocktail Mix",
      Type:          "Сахарный сироп",
      Alc:           0.00,
      Taste:         GetTaste("Сахарный сироп"),
      AviableVolume: []float64{0.360, 0.750},
      Prices:        []float64{5.99, 6.99},
      Description:   &texts.DescProduct[29],
    },
    "Corona Extra Lager Mexican Beer": {
      Name:          "Corona Extra Lager Mexican Beer",
      Type:          "Пиво",
      Alc:           4.60,
      Taste:         GetTaste("Пиво"),
      AviableVolume: []float64{0.500},
      Prices:        []float64{1.80},
      Description:   &texts.DescProduct[30],
    },
    "Cruzan Aged Light Rum": {
      Name:          "Cruzan Aged Light Rum",
      Type:          "Белый ром",
      Alc:           40.00,
      Taste:         GetTaste("Белый ром"),
      AviableVolume: []float64{0.375, 0.750},
      Prices:        []float64{7.99, 13.19},
      Description:   &texts.DescProduct[31],
    },
    "Dailys Simple Syrup": {
      Name:          "Dailys Simple Syrup",
      Type:          "Сахарный сироп",
      Alc:           0.00,
      Taste:         GetTaste("Сахарный сироп"),
      AviableVolume: []float64{0.935},
      Prices:        []float64{6.22},
      Description:   &texts.DescProduct[32],
    },
    "DeKuyper Blue Curacao Liqueur": {
      Name:          "DeKuyper Blue Curacao Liqueur",
      Type:          "Ликер блю кюрасао",
      Alc:           24.00,
      Taste:         GetTaste("Ликер блю кюрасао"),
      AviableVolume: []float64{0.750, 1.000},
      Prices:        []float64{12.09, 13.99},
      Description:   &texts.DescProduct[33],
    },
    "DeLeon Blanco Tequila": {
      Name:          "DeLeon Blanco Tequila",
      Type:          "Серебряная текила",
      Alc:           40.00,
      Taste:         GetTaste("Серебряная текила"),
      AviableVolume: []float64{0.750, 1.750},
      Prices:        []float64{43.89, 62.99},
      Description:   &texts.DescProduct[34],
    },
    "Deep Eddy Lemon Vodka": {
      Name:          "Deep Eddy Lemon Vodka",
      Type:          "Цитрусовая Водка",
      Alc:           35.00,
      Taste:         GetTaste("Цитрусовая Водка"),
      AviableVolume: []float64{0.750, 1.750},
      Prices:        []float64{18.69, 27.99},
      Description:   &texts.DescProduct[35],
    },
    "Dole Limon Juice": {
      Name:          "Dole Limon Juice",
      Type:          "Лимонный сок",
      Alc:           0.00,
      Taste:         GetTaste("Лимонный сок"),
      AviableVolume: []float64{1.360},
      Prices:        []float64{4.77},
      Description:   &texts.DescProduct[36],
    },
    "Dole Pineapple Juice": {
      Name:          "Dole Pineapple Juice",
      Type:          "Ананасовый сок",
      Alc:           0.00,
      Taste:         GetTaste("Ананасовый сок"),
      AviableVolume: []float64{1.360},
      Prices:        []float64{4.99},
      Description:   &texts.DescProduct[37],
    },
    "Don Julio Reposado": {
      Name:          "Don Julio Reposado",
      Type:          "Текила",
      Alc:           40.00,
      Taste:         GetTaste("Текила"),
      AviableVolume: []float64{0.750, 1.750},
      Prices:        []float64{59.99, 114.99},
      Description:   &texts.DescProduct[38],
    },
    "Dried Orange Peel": {
      Name:          "Dried Orange Peel",
      Type:          "Апельсиновая цедра",
      Alc:           0.00,
      Taste:         GetTaste("Апельсиновая цедра"),
      AviableVolume: []float64{0.100},
      Prices:        []float64{2.60},
      Description:   &texts.DescProduct[39],
    },
    "Fruko Schulz Blue Curacao Liqueur": {
      Name:          "Fruko Schulz Blue Curacao Liqueur",
      Type:          "Ликер блю кюрасао Fruko Schulz",
      Alc:           24.00,
      Taste:         GetTaste("Ликер блю кюрасао Fruko Schulz"),
      AviableVolume: []float64{0.700},
      Prices:        []float64{19.71},
      Description:   &texts.DescProduct[40],
    },
    "Fruko Schulz Peach Liqueur": {
      Name:          "Fruko Schulz Peach Liqueur",
      Type:          "Персиковый ликер Fruko Schulz",
      Alc:           20.00,
      Taste:         GetTaste("Персиковый ликер Fruko Schulz"),
      AviableVolume: []float64{0.700},
      Prices:        []float64{21.51},
      Description:   &texts.DescProduct[41],
    },
    "Gold": {
      Name:          "Gold",
      Type:          "Пиво",
      Alc:           6.50,
      Taste:         GetTaste("Пиво"),
      AviableVolume: []float64{1.000, 1.500},
      Prices:        []float64{1.30, 2.00},
      Description:   &texts.DescProduct[42],
    },
    "Gordons London Dry Gin": {
      Name:          "Gordons London Dry Gin",
      Type:          "Лондонский сухой джин",
      Alc:           40.00,
      Taste:         GetTaste("Лондонский сухой джин"),
      AviableVolume: []float64{1.000, 1.750},
      Prices:        []float64{17.99, 22.99},
      Description:   &texts.DescProduct[43],
    },
    "Havana Club Anejo Clasico": {
      Name:          "Havana Club Anejo Clasico",
      Type:          "Ром",
      Alc:           40.00,
      Taste:         GetTaste("Ром"),
      AviableVolume: []float64{0.050, 0.750},
      Prices:        []float64{1.49, 22.99},
      Description:   &texts.DescProduct[44],
    },
    "Havana Club Rum": {
      Name:          "Havana Club Rum",
      Type:          "Белый ром",
      Alc:           40.00,
      Taste:         GetTaste("Белый ром"),
      AviableVolume: []float64{0.050, 0.750},
      Prices:        []float64{1.49, 23.09},
      Description:   &texts.DescProduct[45],
    },
    "Iberica Pineapple Choice Slices": {
      Name:          "Iberica Pineapple Choice Slices",
      Type:          "Ананас",
      Alc:           0.00,
      Taste:         GetTaste("Ананас"),
      AviableVolume: []float64{0.432},
      Prices:        []float64{1.39},
      Description:   &texts.DescProduct[46],
    },
    "Jameson Orange Irish Whiskey": {
      Name:          "Jameson Orange Irish Whiskey",
      Type:          "Ирландский виски",
      Alc:           30.00,
      Taste:         GetTaste("Ирландский виски"),
      AviableVolume: []float64{0.750, 1.500},
      Prices:        []float64{31.99, 54.99},
      Description:   &texts.DescProduct[47],
    },
    "Liqueur Fruko Schulz Triple Sec": {
      Name:          "Liqueur Fruko Schulz Triple Sec",
      Type:          "Трипл сек Fruko Schulz",
      Alc:           40.00,
      Taste:         GetTaste("Трипл сек Fruko Schulz"),
      AviableVolume: []float64{0.700},
      Prices:        []float64{21.43},
      Description:   &texts.DescProduct[48],
    },
    "Martini & Rossi Extra Dry Vermouth": {
      Name:          "Martini & Rossi Extra Dry Vermouth",
      Type:          "Сухой вермут",
      Alc:           15.00,
      Taste:         GetTaste("Сухой вермут"),
      AviableVolume: []float64{0.750},
      Prices:        []float64{10.99},
      Description:   &texts.DescProduct[49],
    },
    "Monin Coconut Syrup": {
      Name:          "Monin Coconut Syrup",
      Type:          "Кокосовый сироп",
      Alc:           0.00,
      Taste:         GetTaste("Кокосовый сироп"),
      AviableVolume: []float64{0.750, 1.000},
      Prices:        []float64{10.57, 12.31},
      Description:   &texts.DescProduct[50],
    },
    "Monin Passion Fruit Syrup": {
      Name:          "Monin Passion Fruit Syrup",
      Type:          "Сироп маракуйи",
      Alc:           0.00,
      Taste:         GetTaste("Сироп маракуйи"),
      AviableVolume: []float64{0.750},
      Prices:        []float64{10.99},
      Description:   &texts.DescProduct[51],
    },
    "New Amsterdam Gin": {
      Name:          "New Amsterdam Gin",
      Type:          "Амстердамский сухой джин",
      Alc:           40.00,
      Taste:         GetTaste("Амстердамский сухой джин"),
      AviableVolume: []float64{0.750, 1.750},
      Prices:        []float64{14.99, 23.10},
      Description:   &texts.DescProduct[52],
    },
    "Ocean Spray Cranberry Juice Cocktail": {
      Name:          "Ocean Spray Cranberry Juice Cocktail",
      Type:          "Клюквенный сок",
      Alc:           0.00,
      Taste:         GetTaste("Клюквенный сок"),
      AviableVolume: []float64{0.946},
      Prices:        []float64{3.99},
      Description:   &texts.DescProduct[53],
    },
    "Opies Red Cocktail Maraschino Cherries": {
      Name:          "Opies Red Cocktail Maraschino Cherries",
      Type:          "Коктейльная вишня красная",
      Alc:           0.00,
      Taste:         GetTaste("Коктейльная вишня красная"),
      AviableVolume: []float64{0.225},
      Prices:        []float64{6.48},
      Description:   &texts.DescProduct[54],
    },
    "Petite Canne Sugar Cane Syrup": {
      Name:          "Petite Canne Sugar Cane Syrup",
      Type:          "Сахарный сироп",
      Alc:           0.00,
      Taste:         GetTaste("Сахарный сироп"),
      AviableVolume: []float64{0.500, 1.000},
      Prices:        []float64{12.00, 24.99},
      Description:   &texts.DescProduct[55],
    },
    "Realime Lime Juice": {
      Name:          "Realime Lime Juice",
      Type:          "Лаймовый сок",
      Alc:           0.00,
      Taste:         GetTaste("Лаймовый сок"),
      AviableVolume: []float64{0.133, 0.236},
      Prices:        []float64{1.59, 2.99},
      Description:   &texts.DescProduct[56],
    },
    "Red Bitter Caffo": {
      Name:          "Red Bitter Caffo",
      Type:          "Красный биттер",
      Alc:           25.00,
      Taste:         GetTaste("Красный биттер"),
      AviableVolume: []float64{0.750},
      Prices:        []float64{28.99},
      Description:   &texts.DescProduct[57],
    },
    "Roca Patrón Silver": {
      Name:          "Roca Patrón Silver",
      Type:          "Серебренная текила",
      Alc:           45.00,
      Taste:         GetTaste("Серебренная текила"),
      AviableVolume: []float64{0.375, 0.750},
      Prices:        []float64{36.99, 69.99},
      Description:   &texts.DescProduct[58],
    },
    "Rose'S Grenadine": {
      Name:          "Rose'S Grenadine",
      Type:          "Гренадин",
      Alc:           0.00,
      Taste:         GetTaste("Гренадин"),
      AviableVolume: []float64{0.357, 0.740},
      Prices:        []float64{4.99, 6.99},
      Description:   &texts.DescProduct[59],
    },
    "Rum Mocambo 20 Year Old": {
      Name:          "Rum Mocambo 20 Year Old",
      Type:          "Ром",
      Alc:           40.00,
      Taste:         GetTaste("Ром"),
      AviableVolume: []float64{0.750},
      Prices:        []float64{42.99},
      Description:   &texts.DescProduct[60],
    },
    "Simply Lemonade": {
      Name:          "Simply Lemonade",
      Type:          "Лимонад",
      Alc:           0.00,
      Taste:         GetTaste("Лимонад"),
      AviableVolume: []float64{0.473, 1.744},
      Prices:        []float64{2.98, 4.99},
      Description:   &texts.DescProduct[61],
    },
    "Sipsmith London Dry Gin": {
      Name:          "Sipsmith London Dry Gin",
      Type:          "Лондонский сухой джин",
      Alc:           41.60,
      Taste:         GetTaste("Лондонский сухой джин"),
      AviableVolume: []float64{0.375, 0.750},
      Prices:        []float64{21.99, 35.99},
      Description:   &texts.DescProduct[62],
    },
    "Sprite": {
      Name:          "Sprite",
      Type:          "Спрайт",
      Alc:           0.00,
      Taste:         GetTaste("Спрайт"),
      AviableVolume: []float64{0.500, 1.000, 1.500, 2.000},
      Prices:        []float64{1.00, 2.00, 3.00, 4.00},
      Description:   &texts.DescProduct[63],
    },
    "Tata Salt | Vacuum Evaporated Iodised Salt ": {
      Name:          "Tata Salt | Vacuum Evaporated Iodised Salt ",
      Type:          "Соль",
      Alc:           0.00,
      Taste:         GetTaste("Соль"),
      AviableVolume: []float64{1.000},
      Prices:        []float64{0.26},
      Description:   &texts.DescProduct[64],
    },
    "Thai Chef FLORIDA NATURALS : Organic Kaffir Lime Leaves": {
      Name:          "Thai Chef FLORIDA NATURALS : Organic Kaffir Lime Leaves",
      Type:          "Листья лайма",
      Alc:           0.00,
      Taste:         GetTaste("Листья лайма"),
      AviableVolume: []float64{1.000, 2.000, 5.000},
      Prices:        []float64{0.20, 0.30, 0.50},
      Description:   &texts.DescProduct[65],
    },
    "Titos Handmade Vodka": {
      Name:          "Titos Handmade Vodka",
      Type:          "Водка",
      Alc:           40.00,
      Taste:         GetTaste("Водка"),
      AviableVolume: []float64{1.000, 1.750},
      Prices:        []float64{28.40, 36.29},
      Description:   &texts.DescProduct[66],
    },
    "Torada Silver": {
      Name:          "Torada Silver",
      Type:          "Серебренная текила",
      Alc:           40.00,
      Taste:         GetTaste("Серебренная текила"),
      AviableVolume: []float64{1.000},
      Prices:        []float64{11.99},
      Description:   &texts.DescProduct[67],
    },
    "Torani Amer": {
      Name:          "Torani Amer",
      Type:          "Креплённое вино",
      Alc:           39.00,
      Taste:         GetTaste("Креплённое вино"),
      AviableVolume: []float64{0.750},
      Prices:        []float64{11.99},
      Description:   &texts.DescProduct[68],
    },
    "Torani French Vanilla": {
      Name:          "Torani French Vanilla",
      Type:          "Ванильный сироп",
      Alc:           0.00,
      Taste:         GetTaste("Ванильный сироп"),
      AviableVolume: []float64{0.750},
      Prices:        []float64{11.99},
      Description:   &texts.DescProduct[69],
    },
    "Torani Orgeat Syrup": {
      Name:          "Torani Orgeat Syrup",
      Type:          "Сахарный сироп",
      Alc:           0.00,
      Taste:         GetTaste("Сахарный сироп"),
      AviableVolume: []float64{0.750},
      Prices:        []float64{11.99},
      Description:   &texts.DescProduct[70],
    },
    "Torani Peppermint Syrup": {
      Name:          "Torani Peppermint Syrup",
      Type:          "Мятный сироп",
      Alc:           0.00,
      Taste:         GetTaste("Мятный сироп"),
      AviableVolume: []float64{0.375, 0.750},
      Prices:        []float64{6.99, 9.99},
      Description:   &texts.DescProduct[71],
    },
    "Torani Sugar Free Coconut Syrup": {
      Name:          "Torani Sugar Free Coconut Syrup",
      Type:          "Кокосовый сироп",
      Alc:           0.00,
      Taste:         GetTaste("Кокосовый сироп"),
      AviableVolume: []float64{0.750},
      Prices:        []float64{11.99},
      Description:   &texts.DescProduct[72],
    },
    "Tropicana Orange Juice": {
      Name:          "Tropicana Orange Juice",
      Type:          "Апельсиновый сок",
      Alc:           0.00,
      Taste:         GetTaste("Апельсиновый сок"),
      AviableVolume: []float64{0.946},
      Prices:        []float64{3.99},
      Description:   &texts.DescProduct[73],
    },
    "Tropicana Ruby Red Grapefruit Juice Beverage": {
      Name:          "Tropicana Ruby Red Grapefruit Juice Beverage",
      Type:          "Грейпфрутовый сок",
      Alc:           0.00,
      Taste:         GetTaste("Грейпфрутовый сок"),
      AviableVolume: []float64{0.450, 0.946},
      Prices:        []float64{2.19, 3.99},
      Description:   &texts.DescProduct[74],
    },
    "Washingtoh Navel": {
      Name:          "Washingtoh Navel",
      Type:          "Апельсин",
      Alc:           0.00,
      Taste:         GetTaste("Апельсин"),
      AviableVolume: []float64{1.000},
      Prices:        []float64{3.00},
      Description:   &texts.DescProduct[75],
    },
    "Апельсины Валенсия": {
      Name:          "Апельсины Валенсия",
      Type:          "Апельсин",
      Alc:           0.00,
      Taste:         GetTaste("Апельсин"),
      AviableVolume: []float64{1.000},
      Prices:        []float64{4.00},
      Description:   &texts.DescProduct[76],
    },
    "Апероль": {
      Name:          "Апероль",
      Type:          "Апероль",
      Alc:           22.00,
      Taste:         GetTaste("Апероль"),
      AviableVolume: []float64{0.750, 1.000},
      Prices:        []float64{27.99, 34.71},
      Description:   &texts.DescProduct[77],
    },
    "Белый Медведь": {
      Name:          "Белый Медведь",
      Type:          "Пиво",
      Alc:           6.20,
      Taste:         GetTaste("Пиво"),
      AviableVolume: []float64{1.000, 1.500},
      Prices:        []float64{1.30, 2.00},
      Description:   &texts.DescProduct[78],
    },
    "Водка Царская": {
      Name:          "Водка Царская",
      Type:          "Водка",
      Alc:           40.00,
      Taste:         GetTaste("Водка"),
      AviableVolume: []float64{0.500},
      Prices:        []float64{5.59},
      Description:   &texts.DescProduct[79],
    },
    "Грейпфрут": {
      Name:          "Грейпфрут",
      Type:          "Грейпфрут",
      Alc:           0.00,
      Taste:         GetTaste("Грейпфрут"),
      AviableVolume: []float64{1.000},
      Prices:        []float64{2.05},
      Description:   &texts.DescProduct[80],
    },
    "Дробленый Лед": {
      Name:          "Дробленый Лед",
      Type:          "Дробленый лед",
      Alc:           0.00,
      Taste:         GetTaste("Дробленый лед"),
      AviableVolume: []float64{1.000, 2.000, 5.000, 10.000},
      Prices:        []float64{0.50, 0.80, 1.50, 2.00},
      Description:   &texts.DescProduct[81],
    },
    "Клинское": {
      Name:          "Клинское",
      Type:          "Пиво",
      Alc:           5.70,
      Taste:         GetTaste("Пиво"),
      AviableVolume: []float64{0.500, 1.000, 1.500},
      Prices:        []float64{0.90, 1.60, 2.00},
      Description:   &texts.DescProduct[82],
    },
    "Лайм": {
      Name:          "Лайм",
      Type:          "Лайм",
      Alc:           0.00,
      Taste:         GetTaste("Лайм"),
      AviableVolume: []float64{1.000, 2.000, 3.000, 5.000},
      Prices:        []float64{6.00, 10.00, 13.00, 16.50},
      Description:   &texts.DescProduct[83],
    },
    "Ледяной Куб": {
      Name:          "Ледяной куб",
      Type:          "Ледяной куб",
      Alc:           0.00,
      Taste:         GetTaste("Ледяной куб"),
      AviableVolume: []float64{1.000, 2.000, 5.000, 10.000},
      Prices:        []float64{0.50, 0.80, 1.50, 2.00},
      Description:   &texts.DescProduct[84],
    },
    "Лед В Кубиках": {
      Name:          "Лед В Кубиках",
      Type:          "Лед в кубиках",
      Alc:           0.00,
      Taste:         GetTaste("Лед в кубиках"),
      AviableVolume: []float64{1.000, 2.000, 5.000, 10.000},
      Prices:        []float64{0.50, 0.80, 1.50, 2.00},
      Description:   &texts.DescProduct[85],
    },
    "Лимон": {
      Name:          "Лимон",
      Type:          "Лимон",
      Alc:           0.00,
      Taste:         GetTaste("Лимон"),
      AviableVolume: []float64{1.000, 2.000, 3.000, 5.000},
      Prices:        []float64{5.00, 8.00, 12.00, 14.00},
      Description:   &texts.DescProduct[86],
    },
    "Обуховская": {
      Name:          "Обуховская",
      Type:          "Обуховская",
      Alc:           0.00,
      Taste:         GetTaste("Обуховская"),
      AviableVolume: []float64{0.500, 1.000, 1.500, 2.000},
      Prices:        []float64{0.50, 0.70, 1.00, 1.20},
      Description:   &texts.DescProduct[87],
    },
    "Просекко": {
      Name:          "Просекко",
      Type:          "Просекко",
      Alc:           11.00,
      Taste:         GetTaste("Просекко"),
      AviableVolume: []float64{0.750},
      Prices:        []float64{14.94},
      Description:   &texts.DescProduct[88],
    },
    "Содовая": {
      Name:          "Содовая",
      Type:          "Содовая",
      Alc:           0.00,
      Taste:         GetTaste("Содовая"),
      AviableVolume: []float64{0.250, 0.500, 1.000, 1.500},
      Prices:        []float64{0.30, 0.50, 0.70, 1.00},
      Description:   &texts.DescProduct[89],
    },
    "Три Медведя": {
      Name:          "Три Медведя",
      Type:          "Пиво",
      Alc:           6.10,
      Taste:         GetTaste("Пиво"),
      AviableVolume: []float64{1.000, 1.500},
      Prices:        []float64{1.30, 2.00},
      Description:   &texts.DescProduct[90],
    },
    "Эбботтс Биттер": {
      Name:          "Эбботтс Биттер",
      Type:          "Биттер",
      Alc:           41.50,
      Taste:         GetTaste("Биттер"),
      AviableVolume: []float64{0.100},
      Prices:        []float64{20.50},
      Description:   &texts.DescProduct[91],
    },
}