package products

import "devllart/foobarman/internal/texts"

var AvailableProducts = map[string]ProductInfo{
    "Ocean Spray Cranberry Juice Cocktail": {
      Name:          "Ocean Spray Cranberry Juice Cocktail",
      Type:          "Клюквенный сок",
      Alc:           0.00,
      Taste:         texts.Tastes1,
      AviableVolume: []float64{0.946},
      Prices:        []float64{3.99},
      Description:   texts.DescCoctail1,
    },
    "Sprite": {
      Name:          "Sprite",
      Type:          "Спрайт",
      Alc:           0.00,
      Taste:         texts.Tastes2,
      AviableVolume: []float64{0.500, 1.000, 1.500, 2.000},
      Prices:        []float64{1.00, 2.00, 3.00, 4.00},
      Description:   texts.DescCoctail2,
    },
    "Torani Peppermint Syrup": {
      Name:          "Torani Peppermint Syrup",
      Type:          "Мятный сироп",
      Alc:           0.00,
      Taste:         texts.Tastes3,
      AviableVolume: []float64{0.375, 0.750},
      Prices:        []float64{6.99, 9.99},
      Description:   texts.DescCoctail3,
    },
    "Апероль": {
      Name:          "Апероль",
      Type:          "Апероль",
      Alc:           22.00,
      Taste:         texts.Tastes4,
      AviableVolume: []float64{0.750, 1.000},
      Prices:        []float64{27.99, 34.71},
      Description:   texts.DescCoctail4,
    },
    "Barsmith Grenadine": {
      Name:          "Barsmith Grenadine",
      Type:          "Гренадин",
      Alc:           0.00,
      Taste:         texts.Tastes5,
      AviableVolume: []float64{0.354},
      Prices:        []float64{4.99},
      Description:   texts.DescCoctail5,
    },
    "Havana Club Rum": {
      Name:          "Havana Club Rum",
      Type:          "Белый ром",
      Alc:           40.00,
      Taste:         texts.Tastes6,
      AviableVolume: []float64{0.050, 0.750},
      Prices:        []float64{1.49, 23.09},
      Description:   texts.DescCoctail6,
    },
    "Jameson Orange Irish Whiskey": {
      Name:          "Jameson Orange Irish Whiskey",
      Type:          "Ирландский виски",
      Alc:           30.00,
      Taste:         texts.Tastes7,
      AviableVolume: []float64{0.750, 1.500},
      Prices:        []float64{31.99, 54.99},
      Description:   texts.DescCoctail7,
    },
    "Водка Царская": {
      Name:          "Водка Царская",
      Type:          "Водка",
      Alc:           40.00,
      Taste:         texts.Tastes8,
      AviableVolume: []float64{0.500},
      Prices:        []float64{5.59},
      Description:   texts.DescCoctail8,
    },
    "Обуховская": {
      Name:          "Обуховская",
      Type:          "Обуховская",
      Alc:           0.00,
      Taste:         texts.Tastes9,
      AviableVolume: []float64{0.500, 1.000, 1.500, 2.000},
      Prices:        []float64{0.50, 0.70, 1.00, 1.20},
      Description:   texts.DescCoctail9,
    },
    "Сливки \"ПРОСТОКВАШИНО\"": {
      Name:          "Сливки \"ПРОСТОКВАШИНО\"",
      Type:          "Сливки",
      Alc:           0.00,
      Taste:         texts.Tastes10,
      AviableVolume: []float64{0.200},
      Prices:        []float64{1.00},
      Description:   texts.DescCoctail10,
    },
    "Don Julio Reposado": {
      Name:          "Don Julio Reposado",
      Type:          "Текила",
      Alc:           40.00,
      Taste:         texts.Tastes11,
      AviableVolume: []float64{0.750, 1.750},
      Prices:        []float64{59.99, 114.99},
      Description:   texts.DescCoctail11,
    },
    "Апельсины Валенсия": {
      Name:          "Апельсины Валенсия",
      Type:          "Апельсин",
      Alc:           0.00,
      Taste:         texts.Tastes12,
      AviableVolume: []float64{1.000},
      Prices:        []float64{4.00},
      Description:   texts.DescCoctail12,
    },
    "Клинское": {
      Name:          "Клинское",
      Type:          "Пиво",
      Alc:           5.70,
      Taste:         texts.Tastes13,
      AviableVolume: []float64{0.500, 1.000, 1.500},
      Prices:        []float64{0.90, 1.60, 2.00},
      Description:   texts.DescCoctail13,
    },
    "Три Медведя": {
      Name:          "Три Медведя",
      Type:          "Пиво",
      Alc:           6.10,
      Taste:         texts.Tastes14,
      AviableVolume: []float64{1.000, 1.500},
      Prices:        []float64{1.30, 2.00},
      Description:   texts.DescCoctail14,
    },
    "Iberica Pineapple Choice Slices": {
      Name:          "Iberica Pineapple Choice Slices",
      Type:          "Ананас",
      Alc:           0.00,
      Taste:         texts.Tastes15,
      AviableVolume: []float64{0.432},
      Prices:        []float64{1.39},
      Description:   texts.DescCoctail15,
    },
    "Лед В Кубиках": {
      Name:          "Лед В Кубиках",
      Type:          "Лед в кубиках",
      Alc:           0.00,
      Taste:         texts.Tastes16,
      AviableVolume: []float64{1.000, 2.000, 5.000, 10.000},
      Prices:        []float64{0.50, 0.80, 1.50, 2.00},
      Description:   texts.DescCoctail16,
    },
    "Absente Absinthe 110 Proof": {
      Name:          "Absente Absinthe 110 proof",
      Type:          "Абсент",
      Alc:           55.00,
      Taste:         texts.Tastes17,
      AviableVolume: []float64{0.100, 0.750},
      Prices:        []float64{11.32, 48.99},
      Description:   texts.DescCoctail17,
    },
    "Fruko Schulz Coffee Liqueur": {
      Name:          "Fruko Schulz coffee liqueur",
      Type:          "Кофейный ликер Fruko Schulz",
      Alc:           20.00,
      Taste:         texts.Tastes18,
      AviableVolume: []float64{0.700},
      Prices:        []float64{20.55},
      Description:   texts.DescCoctail18,
    },
    "Jolly Roger Gold Rum": {
      Name:          "Jolly Roger Gold Rum",
      Type:          "Золотой ром",
      Alc:           40.00,
      Taste:         texts.Tastes19,
      AviableVolume: []float64{0.750},
      Prices:        []float64{12.99},
      Description:   texts.DescCoctail19,
    },
    "BACARDI Spiced Rum": {
      Name:          "BACARDI Spiced Rum",
      Type:          "Ром",
      Alc:           35.00,
      Taste:         texts.Tastes20,
      AviableVolume: []float64{0.750, 1.750},
      Prices:        []float64{15.89, 24.14},
      Description:   texts.DescCoctail20,
    },
    "Bonduelle Olives": {
      Name:          "Bonduelle Olives",
      Type:          "Оливки",
      Alc:           0.00,
      Taste:         texts.Tastes21,
      AviableVolume: []float64{0.300},
      Prices:        []float64{1.49},
      Description:   texts.DescCoctail21,
    },
    "Dole Pineapple Juice": {
      Name:          "Dole Pineapple Juice",
      Type:          "Ананасовый сок",
      Alc:           0.00,
      Taste:         texts.Tastes22,
      AviableVolume: []float64{1.360},
      Prices:        []float64{4.99},
      Description:   texts.DescCoctail22,
    },
    "Monster Energy Drink": {
      Name:          "Monster Energy Drink",
      Type:          "Энергетик",
      Alc:           0.00,
      Taste:         texts.Tastes23,
      AviableVolume: []float64{0.473},
      Prices:        []float64{2.99},
      Description:   texts.DescCoctail23,
    },
    "Bell'S Original Blended Scotch Whisky": {
      Name:          "Bell'S Original Blended Scotch Whisky",
      Type:          "Шотландский виски",
      Alc:           40.00,
      Taste:         texts.Tastes24,
      AviableVolume: []float64{0.750},
      Prices:        []float64{16.81},
      Description:   texts.DescCoctail24,
    },
    "Realime Lime Juice": {
      Name:          "Realime Lime Juice",
      Type:          "Лаймовый сок",
      Alc:           0.00,
      Taste:         texts.Tastes25,
      AviableVolume: []float64{0.133, 0.236},
      Prices:        []float64{1.59, 2.99},
      Description:   texts.DescCoctail25,
    },
    "Irish Manor Irish Cream": {
      Name:          "Irish Manor Irish Cream",
      Type:          "Айриш крим",
      Alc:           17.00,
      Taste:         texts.Tastes26,
      AviableVolume: []float64{0.750, 1.750},
      Prices:        []float64{14.99, 26.12},
      Description:   texts.DescCoctail26,
    },
    "Bud Light": {
      Name:          "Bud Light",
      Type:          "Пиво",
      Alc:           4.70,
      Taste:         texts.Tastes27,
      AviableVolume: []float64{0.500},
      Prices:        []float64{1.70},
      Description:   texts.DescCoctail27,
    },
    "Rum Mocambo 20 Year Old": {
      Name:          "Rum Mocambo 20 Year Old",
      Type:          "Ром",
      Alc:           40.00,
      Taste:         texts.Tastes28,
      AviableVolume: []float64{0.750},
      Prices:        []float64{42.99},
      Description:   texts.DescCoctail28,
    },
    "Клубничное Пюре": {
      Name:          "Клубничное Пюре",
      Type:          "Клубничное пюре",
      Alc:           0.00,
      Taste:         texts.Tastes29,
      AviableVolume: []float64{1.000},
      Prices:        []float64{1.00},
      Description:   texts.DescCoctail29,
    },
    "Bud": {
      Name:          "Bud",
      Type:          "Пиво",
      Alc:           5.90,
      Taste:         texts.Tastes30,
      AviableVolume: []float64{0.500},
      Prices:        []float64{1.10},
      Description:   texts.DescCoctail30,
    },
    "Cointreau Orange Liqueur Triple Sec": {
      Name:          "Cointreau Orange Liqueur Triple Sec",
      Type:          "Трипл сек",
      Alc:           40.00,
      Taste:         texts.Tastes31,
      AviableVolume: []float64{0.750, 1.000},
      Prices:        []float64{40.65, 45.97},
      Description:   texts.DescCoctail31,
    },
    "Torani Sugar Free Coconut Syrup": {
      Name:          "Torani Sugar Free Coconut Syrup",
      Type:          "Кокосовый сироп",
      Alc:           0.00,
      Taste:         texts.Tastes32,
      AviableVolume: []float64{0.750},
      Prices:        []float64{11.99},
      Description:   texts.DescCoctail32,
    },
    "Лимон": {
      Name:          "Лимон",
      Type:          "Лимон",
      Alc:           0.00,
      Taste:         texts.Tastes33,
      AviableVolume: []float64{1.000, 2.000, 3.000, 5.000},
      Prices:        []float64{5.00, 8.00, 12.00, 14.00},
      Description:   texts.DescCoctail33,
    },
    "Fruko Schulz Blue Curacao Liqueur": {
      Name:          "Fruko Schulz Blue Curacao Liqueur",
      Type:          "Ликер блю кюрасао Fruko Schulz",
      Alc:           24.00,
      Taste:         texts.Tastes34,
      AviableVolume: []float64{0.700},
      Prices:        []float64{19.71},
      Description:   texts.DescCoctail34,
    },
    "Sipsmith London Dry Gin": {
      Name:          "Sipsmith London Dry Gin",
      Type:          "Лондонский сухой джин",
      Alc:           41.60,
      Taste:         texts.Tastes35,
      AviableVolume: []float64{0.375, 0.750},
      Prices:        []float64{21.99, 35.99},
      Description:   texts.DescCoctail35,
    },
    "Amaretto Liqueur Fruko Schulz": {
      Name:          "Amaretto Liqueur Fruko Schulz",
      Type:          "Ликер амаретто Fruko Schulz",
      Alc:           25.00,
      Taste:         texts.Tastes36,
      AviableVolume: []float64{0.700},
      Prices:        []float64{20.45},
      Description:   texts.DescCoctail36,
    },
    "Stroh Rum 160 Proof": {
      Name:          "Stroh Rum 160 Proof",
      Type:          "Сверхкрепкий ром",
      Alc:           80.00,
      Taste:         texts.Tastes37,
      AviableVolume: []float64{0.750},
      Prices:        []float64{33.99},
      Description:   texts.DescCoctail37,
    },
    "BACARDI Black Rum": {
      Name:          "BACARDI Black Rum",
      Type:          "Темный ром",
      Alc:           40.00,
      Taste:         texts.Tastes38,
      AviableVolume: []float64{0.200, 0.750},
      Prices:        []float64{5.49, 15.49},
      Description:   texts.DescCoctail38,
    },
    "Bombay Dry Gin": {
      Name:          "Bombay Dry Gin",
      Type:          "Лондонский сухой джин",
      Alc:           43.00,
      Taste:         texts.Tastes39,
      AviableVolume: []float64{0.750, 1.750},
      Prices:        []float64{22.99, 34.49},
      Description:   texts.DescCoctail39,
    },
    "Corona Extra Lager Mexican Beer": {
      Name:          "Corona Extra Lager Mexican Beer",
      Type:          "Пиво",
      Alc:           4.60,
      Taste:         texts.Tastes40,
      AviableVolume: []float64{0.500},
      Prices:        []float64{1.80},
      Description:   texts.DescCoctail40,
    },
    "Deep Eddy Lemon Vodka": {
      Name:          "Deep Eddy Lemon Vodka",
      Type:          "Цитрусовая Водка",
      Alc:           35.00,
      Taste:         texts.Tastes41,
      AviableVolume: []float64{0.750, 1.750},
      Prices:        []float64{18.69, 27.99},
      Description:   texts.DescCoctail41,
    },
    "Грейпфрут": {
      Name:          "Грейпфрут",
      Type:          "Грейпфрут",
      Alc:           0.00,
      Taste:         texts.Tastes42,
      AviableVolume: []float64{1.000},
      Prices:        []float64{2.05},
      Description:   texts.DescCoctail42,
    },
    "Клубника": {
      Name:          "Клубника",
      Type:          "Клубника",
      Alc:           0.00,
      Taste:         texts.Tastes43,
      AviableVolume: []float64{1.000},
      Prices:        []float64{1.00},
      Description:   texts.DescCoctail43,
    },
    "Monin Cinnamon Bun": {
      Name:          "Monin Cinnamon Bun",
      Type:          "Сироп корицы",
      Alc:           0.00,
      Taste:         texts.Tastes44,
      AviableVolume: []float64{0.750},
      Prices:        []float64{7.99},
      Description:   texts.DescCoctail44,
    },
    "DeLeon Blanco Tequila": {
      Name:          "DeLeon Blanco Tequila",
      Type:          "Серебряная текила",
      Alc:           40.00,
      Taste:         texts.Tastes45,
      AviableVolume: []float64{0.750, 1.750},
      Prices:        []float64{43.89, 62.99},
      Description:   texts.DescCoctail45,
    },
    "Monin Coconut Syrup": {
      Name:          "Monin Coconut Syrup",
      Type:          "Кокосовый сироп",
      Alc:           0.00,
      Taste:         texts.Tastes46,
      AviableVolume: []float64{0.750, 1.000},
      Prices:        []float64{10.57, 12.31},
      Description:   texts.DescCoctail46,
    },
    "New Amsterdam Gin": {
      Name:          "New Amsterdam Gin",
      Type:          "Амстердамский сухой джин",
      Alc:           40.00,
      Taste:         texts.Tastes47,
      AviableVolume: []float64{0.750, 1.750},
      Prices:        []float64{14.99, 23.10},
      Description:   texts.DescCoctail47,
    },
    "Torani Orgeat Syrup": {
      Name:          "Torani Orgeat Syrup",
      Type:          "Сахарный сироп",
      Alc:           0.00,
      Taste:         texts.Tastes48,
      AviableVolume: []float64{0.750},
      Prices:        []float64{11.99},
      Description:   texts.DescCoctail48,
    },
    "Red Bull": {
      Name:          "Red Bull",
      Type:          "Энергетик",
      Alc:           0.00,
      Taste:         texts.Tastes49,
      AviableVolume: []float64{0.248, 0.473},
      Prices:        []float64{2.89, 4.59},
      Description:   texts.DescCoctail49,
    },
    "Collins Simple Syrup Cocktail Mix": {
      Name:          "Collins Simple Syrup Cocktail Mix",
      Type:          "Сахарный сироп",
      Alc:           0.00,
      Taste:         texts.Tastes50,
      AviableVolume: []float64{0.360, 0.750},
      Prices:        []float64{5.99, 6.99},
      Description:   texts.DescCoctail50,
    },
    "Cruzan Aged Light Rum": {
      Name:          "Cruzan Aged Light Rum",
      Type:          "Белый ром",
      Alc:           40.00,
      Taste:         texts.Tastes51,
      AviableVolume: []float64{0.375, 0.750},
      Prices:        []float64{7.99, 13.19},
      Description:   texts.DescCoctail51,
    },
    "Fruko Schulz Peach Liqueur": {
      Name:          "Fruko Schulz Peach Liqueur",
      Type:          "Персиковый ликер Fruko Schulz",
      Alc:           20.00,
      Taste:         texts.Tastes52,
      AviableVolume: []float64{0.700},
      Prices:        []float64{21.51},
      Description:   texts.DescCoctail52,
    },
    "Roca Patrón Silver": {
      Name:          "Roca Patrón Silver",
      Type:          "Серебренная текила",
      Alc:           45.00,
      Taste:         texts.Tastes53,
      AviableVolume: []float64{0.375, 0.750},
      Prices:        []float64{36.99, 69.99},
      Description:   texts.DescCoctail53,
    },
    "Titos Handmade Vodka": {
      Name:          "Titos Handmade Vodka",
      Type:          "Водка",
      Alc:           40.00,
      Taste:         texts.Tastes54,
      AviableVolume: []float64{1.000, 1.750},
      Prices:        []float64{28.40, 36.29},
      Description:   texts.DescCoctail54,
    },
    "Gordons London Dry Gin": {
      Name:          "Gordons London Dry Gin",
      Type:          "Лондонский сухой джин",
      Alc:           40.00,
      Taste:         texts.Tastes55,
      AviableVolume: []float64{1.000, 1.750},
      Prices:        []float64{17.99, 22.99},
      Description:   texts.DescCoctail55,
    },
    "Liqueur Fruko Schulz Triple Sec": {
      Name:          "Liqueur Fruko Schulz Triple Sec",
      Type:          "Трипл сек Fruko Schulz",
      Alc:           40.00,
      Taste:         texts.Tastes56,
      AviableVolume: []float64{0.700},
      Prices:        []float64{21.43},
      Description:   texts.DescCoctail56,
    },
    "Tropicana Ruby Red Grapefruit Juice Beverage": {
      Name:          "Tropicana Ruby Red Grapefruit Juice Beverage",
      Type:          "Грейпфрутовый сок",
      Alc:           0.00,
      Taste:         texts.Tastes57,
      AviableVolume: []float64{0.450, 0.946},
      Prices:        []float64{2.19, 3.99},
      Description:   texts.DescCoctail57,
    },
    "Washingtoh Navel": {
      Name:          "Washingtoh Navel",
      Type:          "Апельсин",
      Alc:           0.00,
      Taste:         texts.Tastes58,
      AviableVolume: []float64{1.000},
      Prices:        []float64{3.00},
      Description:   texts.DescCoctail58,
    },
    "Просекко": {
      Name:          "Просекко",
      Type:          "Просекко",
      Alc:           11.00,
      Taste:         texts.Tastes59,
      AviableVolume: []float64{0.750},
      Prices:        []float64{14.94},
      Description:   texts.DescCoctail59,
    },
    "Torada Silver": {
      Name:          "Torada Silver",
      Type:          "Серебренная текила",
      Alc:           40.00,
      Taste:         texts.Tastes60,
      AviableVolume: []float64{1.000},
      Prices:        []float64{11.99},
      Description:   texts.DescCoctail60,
    },
    "Torani Amer": {
      Name:          "Torani Amer",
      Type:          "Креплённое вино",
      Alc:           39.00,
      Taste:         texts.Tastes61,
      AviableVolume: []float64{0.750},
      Prices:        []float64{11.99},
      Description:   texts.DescCoctail61,
    },
    "Cherry Bomb Cocktail Syrup": {
      Name:          "Cherry Bomb Cocktail Syrup",
      Type:          "Сахарный сироп",
      Alc:           0.00,
      Taste:         texts.Tastes62,
      AviableVolume: []float64{0.400},
      Prices:        []float64{19.00},
      Description:   texts.DescCoctail62,
    },
    "Gold": {
      Name:          "Gold",
      Type:          "Пиво",
      Alc:           6.50,
      Taste:         texts.Tastes63,
      AviableVolume: []float64{1.000, 1.500},
      Prices:        []float64{1.30, 2.00},
      Description:   texts.DescCoctail63,
    },
    "Martini & Rossi Extra Dry Vermouth": {
      Name:          "Martini & Rossi Extra Dry Vermouth",
      Type:          "Сухой вермут",
      Alc:           15.00,
      Taste:         texts.Tastes64,
      AviableVolume: []float64{0.750},
      Prices:        []float64{10.99},
      Description:   texts.DescCoctail64,
    },
    "Simply Lemonade": {
      Name:          "Simply Lemonade",
      Type:          "Лимонад",
      Alc:           0.00,
      Taste:         texts.Tastes65,
      AviableVolume: []float64{0.473, 1.744},
      Prices:        []float64{2.98, 4.99},
      Description:   texts.DescCoctail65,
    },
    "Tata Salt | Vacuum Evaporated Iodised Salt ": {
      Name:          "Tata Salt | Vacuum Evaporated Iodised Salt ",
      Type:          "Соль",
      Alc:           0.00,
      Taste:         texts.Tastes66,
      AviableVolume: []float64{1.000},
      Prices:        []float64{0.26},
      Description:   texts.DescCoctail66,
    },
    "Thai Chef FLORIDA NATURALS : Organic Kaffir Lime Leaves": {
      Name:          "Thai Chef FLORIDA NATURALS : Organic Kaffir Lime Leaves",
      Type:          "Листья лайма",
      Alc:           0.00,
      Taste:         texts.Tastes67,
      AviableVolume: []float64{1.000, 2.000, 5.000},
      Prices:        []float64{0.20, 0.30, 0.50},
      Description:   texts.DescCoctail67,
    },
    "Малина": {
      Name:          "Малина",
      Type:          "Малина",
      Alc:           0.00,
      Taste:         texts.Tastes68,
      AviableVolume: []float64{1.000},
      Prices:        []float64{1.00},
      Description:   texts.DescCoctail68,
    },
    "DeKuyper Blue Curacao Liqueur": {
      Name:          "DeKuyper Blue Curacao Liqueur",
      Type:          "Ликер блю кюрасао",
      Alc:           24.00,
      Taste:         texts.Tastes69,
      AviableVolume: []float64{0.750, 1.000},
      Prices:        []float64{12.09, 13.99},
      Description:   texts.DescCoctail69,
    },
    "Havana Club Anejo Clasico": {
      Name:          "Havana Club Anejo Clasico",
      Type:          "Ром",
      Alc:           40.00,
      Taste:         texts.Tastes70,
      AviableVolume: []float64{0.050, 0.750},
      Prices:        []float64{1.49, 22.99},
      Description:   texts.DescCoctail70,
    },
    "Лайм": {
      Name:          "Лайм",
      Type:          "Лайм",
      Alc:           0.00,
      Taste:         texts.Tastes71,
      AviableVolume: []float64{1.000, 2.000, 3.000, 5.000},
      Prices:        []float64{6.00, 10.00, 13.00, 16.50},
      Description:   texts.DescCoctail71,
    },
    "Opies Red Cocktail Maraschino Cherries": {
      Name:          "Opies Red Cocktail Maraschino Cherries",
      Type:          "Коктейльная вишня красная",
      Alc:           0.00,
      Taste:         texts.Tastes72,
      AviableVolume: []float64{0.225},
      Prices:        []float64{6.48},
      Description:   texts.DescCoctail72,
    },
    "Tropicana Orange Juice": {
      Name:          "Tropicana Orange Juice",
      Type:          "Апельсиновый сок",
      Alc:           0.00,
      Taste:         texts.Tastes73,
      AviableVolume: []float64{0.946},
      Prices:        []float64{3.99},
      Description:   texts.DescCoctail73,
    },
    "Barsmith Simple Syrup": {
      Name:          "Barsmith Simple Syrup",
      Type:          "Сахарный сироп",
      Alc:           0.00,
      Taste:         texts.Tastes74,
      AviableVolume: []float64{0.360},
      Prices:        []float64{4.99},
      Description:   texts.DescCoctail74,
    },
    "Belsazar Vermouth": {
      Name:          "Belsazar Vermouth",
      Type:          "Красный вермут",
      Alc:           40.00,
      Taste:         texts.Tastes75,
      AviableVolume: []float64{0.375, 0.750},
      Prices:        []float64{7.99, 13.19},
      Description:   texts.DescCoctail75,
    },
    "Bioniq Mint": {
      Name:          "Bioniq Mint",
      Type:          "Мята",
      Alc:           0.00,
      Taste:         texts.Tastes76,
      AviableVolume: []float64{0.035},
      Prices:        []float64{1.09},
      Description:   texts.DescCoctail76,
    },
    "Coca-Cola": {
      Name:          "Coca-Cola",
      Type:          "Кола",
      Alc:           0.00,
      Taste:         texts.Tastes77,
      AviableVolume: []float64{0.500, 1.000, 1.500, 2.000},
      Prices:        []float64{1.00, 2.00, 3.00, 4.00},
      Description:   texts.DescCoctail77,
    },
    "Dailys Simple Syrup": {
      Name:          "Dailys Simple Syrup",
      Type:          "Сахарный сироп",
      Alc:           0.00,
      Taste:         texts.Tastes78,
      AviableVolume: []float64{0.935},
      Prices:        []float64{6.22},
      Description:   texts.DescCoctail78,
    },
    "Monin Passion Fruit Syrup": {
      Name:          "Monin Passion Fruit Syrup",
      Type:          "Сироп маракуйи",
      Alc:           0.00,
      Taste:         texts.Tastes79,
      AviableVolume: []float64{0.750},
      Prices:        []float64{10.99},
      Description:   texts.DescCoctail79,
    },
    "Дробленый Лед": {
      Name:          "Дробленый Лед",
      Type:          "Дробленый лед",
      Alc:           0.00,
      Taste:         texts.Tastes80,
      AviableVolume: []float64{1.000, 2.000, 5.000, 10.000},
      Prices:        []float64{0.50, 0.80, 1.50, 2.00},
      Description:   texts.DescCoctail80,
    },
    "Содовая": {
      Name:          "Содовая",
      Type:          "Содовая",
      Alc:           0.00,
      Taste:         texts.Tastes81,
      AviableVolume: []float64{0.250, 0.500, 1.000, 1.500},
      Prices:        []float64{0.30, 0.50, 0.70, 1.00},
      Description:   texts.DescCoctail81,
    },
    "Эбботтс Биттер": {
      Name:          "Эбботтс Биттер",
      Type:          "Биттер",
      Alc:           41.50,
      Taste:         texts.Tastes82,
      AviableVolume: []float64{0.100},
      Prices:        []float64{20.50},
      Description:   texts.DescCoctail82,
    },
    "Jack Daniel'S Old No. 7 Tennessee Whiskey": {
      Name:          "Jack Daniel's Old No. 7 Tennessee Whiskey",
      Type:          "Виски",
      Alc:           40.00,
      Taste:         texts.Tastes83,
      AviableVolume: []float64{0.750, 1.000},
      Prices:        []float64{26.60, 36.99},
      Description:   texts.DescCoctail83,
    },
    "Dried Orange Peel": {
      Name:          "Dried Orange Peel",
      Type:          "Апельсиновая цедра",
      Alc:           0.00,
      Taste:         texts.Tastes84,
      AviableVolume: []float64{0.100},
      Prices:        []float64{2.60},
      Description:   texts.DescCoctail84,
    },
    "Petite Canne Sugar Cane Syrup": {
      Name:          "Petite Canne Sugar Cane Syrup",
      Type:          "Сахарный сироп",
      Alc:           0.00,
      Taste:         texts.Tastes85,
      AviableVolume: []float64{0.500, 1.000},
      Prices:        []float64{12.00, 24.99},
      Description:   texts.DescCoctail85,
    },
    "Red Bitter Caffo": {
      Name:          "Red Bitter Caffo",
      Type:          "Красный биттер",
      Alc:           25.00,
      Taste:         texts.Tastes86,
      AviableVolume: []float64{0.750},
      Prices:        []float64{28.99},
      Description:   texts.DescCoctail86,
    },
    "Torani French Vanilla": {
      Name:          "Torani French Vanilla",
      Type:          "Ванильный сироп",
      Alc:           0.00,
      Taste:         texts.Tastes87,
      AviableVolume: []float64{0.750},
      Prices:        []float64{11.99},
      Description:   texts.DescCoctail87,
    },
    "Белый Медведь": {
      Name:          "Белый Медведь",
      Type:          "Пиво",
      Alc:           6.20,
      Taste:         texts.Tastes88,
      AviableVolume: []float64{1.000, 1.500},
      Prices:        []float64{1.30, 2.00},
      Description:   texts.DescCoctail88,
    },
    "Jim Beam Bourbon Whiskey": {
      Name:          "Jim Beam Bourbon Whiskey",
      Type:          "Бурбон",
      Alc:           40.00,
      Taste:         texts.Tastes89,
      AviableVolume: []float64{1.000, 1.750},
      Prices:        []float64{24.99, 31.99},
      Description:   texts.DescCoctail89,
    },
    "Dole Limon Juice": {
      Name:          "Dole Limon Juice",
      Type:          "Лимонный сок",
      Alc:           0.00,
      Taste:         texts.Tastes90,
      AviableVolume: []float64{1.360},
      Prices:        []float64{4.77},
      Description:   texts.DescCoctail90,
    },
    "Rose'S Grenadine": {
      Name:          "Rose'S Grenadine",
      Type:          "Гренадин",
      Alc:           0.00,
      Taste:         texts.Tastes91,
      AviableVolume: []float64{0.357, 0.740},
      Prices:        []float64{4.99, 6.99},
      Description:   texts.DescCoctail91,
    },
    "Ледяной Куб": {
      Name:          "Ледяной куб",
      Type:          "Ледяной куб",
      Alc:           0.00,
      Taste:         texts.Tastes92,
      AviableVolume: []float64{1.000, 2.000, 5.000, 10.000},
      Prices:        []float64{0.50, 0.80, 1.50, 2.00},
      Description:   texts.DescCoctail92,
    },
}